# 网站基本信息
title: "杂货铺" # 网站标题
email: xuwentaokif@163.com # 网站联系邮箱
baseurl: "" # 网站根目录（相对于域名），通常是空字符串，除非你的网站部署在子目录下
subtitle: "上班可真累啊" # 网站副标题
description: "记录一些杂乱的东西." # 网站描述，用于SEO
author: "徐文韬" # 网站作者
logo: "/assets/images/sunShine.png" # 网站logo的路径

# Build settings
markdown: kramdown # Markdown处理器，kramdown是Jekyll默认的处理器
theme: minima # 使用的主题，例如minima或jekyll-theme-cayman
#plugins:
#  - jekyll-feed # 启用RSS Feed插件
#  - jekyll-sitemap # 启用Sitemap插件

# 文章相关配置
#timezone: "Beijing" # 时区设置
#highlighter: rouge # 代码高亮引擎
#lsi: false # 是否使用语言隔离索引
#excerpt_separator: "\n\n" # 文章摘要分隔符
#incremental: false # 是否增量生成

# 导航菜单
nav_links:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Contact"
    url: "/contact/"